apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-datasrc
  labels:
    grafana_datasource: "true"
stringData:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true